project:
  type: website
  pre-render: _scripts/generate_qmd.R
execute:
  echo: false
  message: false
  warning: false
  fig.align: center
  out.width: 100%
  freeze: false
website:
  title: "APSIM NG Crops"
  google-analytics: 
    tracking-id: "G-5K7WTC1T5R"
    storage: "cookies"
  site-url: https://apsimng-crops.bangyou.me
  repo-url: "https://github.com/byzheng/apsimng-crops"
  repo-actions: [edit, issue]
  search:
    show-item-context: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/byzheng/apsimng-crops

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

