name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  prepare:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/byzheng/apsimx-quarto-podman:latest
    permissions:
      contents: write

    outputs:
      groups: ${{ steps.groups.outputs.groups }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Data Repository
        uses: actions/checkout@v4
        with:
          repository: byzheng/apsimng-crops-data
          path: _data

      - name: Generate qmd files
        run: Rscript _scripts/generate_qmd.R

      - name: Read render groups
        id: groups
        run: |
          # _render_groups.json contains a JSON array of arrays
          echo "groups=$(cat _render_groups.json)" >> $GITHUB_OUTPUT


      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .
          include-hidden-files: true


  render-files:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/byzheng/apsimx-quarto-podman:latest

    strategy:
      fail-fast: false
      matrix:
        group_id: ${{ range(0, fromJson(needs.prepare.outputs.groups).length) }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - name: Render Group Files
        env:
          R_PROFILE_USER: ${{ github.workspace }}/.Rprofile
        run: |
          files=$(jq -r ".[$GROUP_ID][]" _render_groups.json)
          for file in $files; do
            echo "Rendering $file"
            quarto render "$file"
          done

      - name: Upload site fragment
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ strategy.job-index }}
          path: _site


  deploy:
    needs: render-files
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/byzheng/apsimx-quarto-podman:latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .

      - uses: actions/download-artifact@v4
        with:
          pattern: site-*
          path: site-parts

      - name: Render global pages
        env:
          R_PROFILE_USER: ${{ github.workspace }}/.Rprofile
        run: |
          quarto render index.qmd
          quarto render about.qmd

      - name: Merge site parts
        run: |
          mkdir -p final_site
          # Copy main _site (global pages)
          cp -r _site/* final_site/

          # Loop through all matrix site uploads
          for dir in site-parts/site-*; do
            if [ -d "$dir/_site" ]; then
              cp -r "$dir/_site/"* final_site/
            fi
          done

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: final_site