name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:

  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      crops: ${{ steps.crops.outputs.crops }}

    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'
      - name: Install system dependencies 
        run: | 
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libpng-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            gdal-bin \
            proj-bin \
            libfontconfig1-dev \
            libfreetype6-dev

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Compile APSIMX
        uses: byzheng/apsimx-actions@main

      - name: Checkout Data Repository
        uses: actions/checkout@v4
        with:
          repository: byzheng/apsimng-crops-data
          path: _data

      - name: Generate qmd files
        run: Rscript _scripts/generate_qmd.R

      - name: Detect crops
        id: crops
        run: |
          echo "crops=$(ls crop | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  render-crops:
    needs: prepare
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        crop: ${{ fromJson(needs.prepare.outputs.crops) }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Compile APSIMX
        uses: byzheng/apsimx-actions@main

      - name: Render crop
        run: quarto render crop/${{ matrix.crop }}

      - name: Upload site part
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ matrix.crop }}
          path: _site

  deploy:
    needs: render-crops
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render global pages
        run: |
          quarto render index.qmd
          quarto render about.qmd

      - name: Merge site parts
        run: |
          mkdir final_site
          cp -r site-*/** final_site/ || true
          cp -r _site/* final_site/

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: final_site

